stages:
    - pre-build
    - build
    - test

cargo_build:
    script:
        - cargo build --features "clippy"      
        - ./target/debug/rusty-gopher --version
    tags: 
        - rust
    stage: build

cargo_test:
    script: cargo test
    tags: 
        - rust
    stage: test
